### ISSUE TITLE
Error running demo on Ubuntu 22.04

### ISSUE THREAD

**Issue by davide445** [mimesis-inria/DeepPhysX#6]
Tried installing all except Caribou, but trying to launch the demo i get this error

`user@eGPULinux:~/Downloads/DeepPhysX/Core$ python3 demo.py liver
Traceback (most recent call last):
  File "/home/user/Downloads/DeepPhysX/Core/examples/demos/Liver/FC/interactive.py", line 19, in <module>
    LiverDownloader().get_session('predict')
  File "/home/user/.local/lib/python3.10/site-packages/DeepPhysX/Core/Utils/data_downloader.py", line 55, in get_session
    self.check_tree(session_name)
  File "/home/user/.local/lib/python3.10/site-packages/DeepPhysX/Core/Utils/data_downloader.py", line 84, in check_tree
    if not os.path.exists(os.path.join(self.root, self.tree[last_level], self.filenames[file])):
KeyError: 276
`

**Comment by RobinEnjalbert** [comment]
Hello @davide445 , thanks a lot for reporting your bug.

I am about to release the new version of DeepPhysX (should appear in the coming days) and this affects the previous version of the demos.

The data used to run them (training data & trained network) are stored online on a Dataverse and automatically collected by the ``data_downloader.py`` script. To match the new version of the framework, I had to update some online files, which changed their ID. This is why you have this "KeyError 276" since this ID is no longer existing in the published version of the dataset. You will actually have the same issue with all dataset related files.

Finally, the dataset files are important since they contain normalization coefficient that needs to be applied. So, I see two options for you to be able to run the demos:
1. Editing the ``examples/demos/Liver/FC/download.py`` script. You can replace the list of "dataset_info" with [331] and empty the two lists above.
2. Switching to the "sql_database" branch of all packages since they are stable now and pretty close to the new release.
3. Waiting for the new release (similar to 2. except if you want your packages to be installed with ``pip`` and not from sources.

I hope it will help you !
